name: Pre-commit
description: GitHub Action for running pre-commit hooks against the repository. Conditionally installs tools needed for the Action to be able to perform its duties such as `npm`, `pre-commit`, etc.
inputs:
  config-file:
    required: true
    description: The config file to present to commitlint-github-action
    default: .commitlintrc.yaml
  turo-conventional-commit:
    required: true
    description: Set this to "false" to customize conventional commit configuration
    default: "true"
  only-changed:
    required: false
    description: >-
      Set this to "true" to only run pre-commit against changed files, and not
      the entire repository

runs:
  using: composite
  steps:
    - name: Set node.js version
      if: hashFiles('.node-version') == ''
      shell: bash
      run: |
        # Get the existing node version, if the command exists
        desired_version="$(node --version || true)"
        # Chain defaults to get a good value
        desired_version="${desired_version:-${NODENV_VERSION:-${NODE_VERSION:-16.14.2}}}"
        # Strip the leading "v" in e.g. "v16.0.0", since .node-version will not work with it
        desired_version="${desired_version#v}"
        # Set the version so action-setup-tools can use it later
        echo "$desired_version" > .node-version
    - name: Set Python version
      if: hashFiles('.python-version') == ''
      shell: bash
      run: |
        # Use the .python-version from the action repo as the default version
        PYTHON_VERSION="${PYTHON_VERSION:-$(cat "$GITHUB_ACTION_PATH/.python-version")}"
        echo "$PYTHON_VERSION" > .python-version
        echo "PYTHON_VERSION=${PYTHON_VERSION}" >> "$GITHUB_ENV"
    - name: Find pre-commit
      shell: bash
      run: |
        # Finding pre-commit
        # This will set an environment variable we can use to conditionally
        # install pre-commit if needed and toggle how the action runs.
        echo "PRE_COMMIT_BIN=$(command -v pre-commit)" >> $GITHUB_ENV
    - name: Find python
      shell: bash
      run: |
        # Finding python
        # This will set an environment variable we can use to conditionally
        # install python.
        echo "PYTHON_BIN=$(command -v python3)" >> $GITHUB_ENV
    - name: Setup python
      # Only run this if we don't already have a pre-commit on the PATH
      if: env.PYTHON_BIN == null
      uses: actions/setup-python@v4
      # with:
      #   python-version: 3.10.2
    - name: Install tools
      # This will skip the (slow) pyenv install if we triggered the above
      uses: open-turo/action-setup-tools@v1
    - name: Install @commitlint/cli
      shell: bash
      run: |
        npm install --no-save --no-package-lock --no-audit --no-fund \
          --prefix "$RUNNER_TEMP" "@commitlint/cli"
        echo "$RUNNER_TEMP/node_modules/.bin" >> $GITHUB_PATH
        echo "NODE_PATH=$RUNNER_TEMP/node_modules" >> $GITHUB_ENV
    - name: Use default conventional commit config
      if: inputs.turo-conventional-commit == 'true'
      shell: bash
      run: |
        # Write default commitlint config in the workspace.
        echo "extends: [\"@open-turo/commitlint-config-conventional\"]" \
          > "${{ inputs.config-file }}"
        # XXX(shakefu): We have to list @commitlint/cli here otherwise `npm
        # install` will try to remove it from the above step. There is no way to
        # prevent this behavior that I'm aware of.
        npm install --no-save --no-package-lock --no-audit --no-fund \
          --prefix "$RUNNER_TEMP" \
          "@open-turo/commitlint-config-conventional" \
          "@commitlint/cli"
    - name: Commitlint
      if: hashFiles(inputs.config-file) != ''
      shell: bash
      run: |
        # Commitlint
        # Look for the base ref to compare against the current head in the
        # pull_request event metadata.
        if [[ -z "$FROM" ]]; then
          FROM="${{ github.event.pull_request.base.ref }}"
          if [[ -n "$FROM" ]]; then
            echo "::notice::Parsing base ref '$FROM'"
            # If we do have the base ref, it can be a branch name, so we want to
            # parse it. This will be a pass through for a SHA
            FROM="$(git show-ref --hash "$FROM" | tail -n1)"
          fi
        fi
        # If we don't have a base ref, we try to find the history to the default
        # branch, e.g. main, which should be a sane check.
        if [[ -z "$FROM" ]]; then
          # This finds the default branch name from the remote information, e.g. "main", and then parses it to a SHA
          FROM="$(git show-ref --hash "$(git remote show $(git remote -v | grep push | awk '{print $2}') | grep 'HEAD branch' | awk '{print $3}')" | tail -n1)"
          echo "::notice::Could not find base ref, trying to use default branch"
          if ! git merge-base --is-ancestor "$FROM" HEAD; then
            echo "::warning::Default branch is not an ancestor of HEAD"
            FROM=""
          fi
        fi
        # If the pull_request event metadata doesn't exist, try to grab the
        # "before" commit from the push event metadata. This will usually only
        # give us a single commit to check, but it'll be the latest one.
        if [[ -z "$FROM" ]]; then
          # This is a SHA so no parsing needed
          FROM="${{ github.event.before }}"
          echo "::warning::Could not find ancestor ref, falling back"
          if ! git merge-base --is-ancestor "$FROM" HEAD; then
            echo "::warning::Before commit $FROM is not an ancestor of HEAD"
          else
            echo "::notice::Checking commits since $FROM (usually the latest commit)."
          fi
        fi
        # Default to looking at the last 20 commits otherwise.
        if [[ -z "$FROM" ]]; then
          FROM="HEAD~20"
          echo "::warning::Could not find commit range for commitlint"
          echo "::notice::Checking 20 most recent commit messages."
        fi
        commitlint --config "${{ inputs.config-file }}" \
          --verbose \
          --color \
          --from "$FROM" \
          --to HEAD
    - name: Restore commitlint config
      if: always() && hashFiles(inputs.config-file) != '' && inputs.turo-conventional-commit == 'true'
      shell: bash
      run: git checkout -- "${{ inputs.config-file }}" || true
    # Collect file changes
    - name: Find changed files
      if: inputs.only-changed == 'true'
      uses: trilom/file-changes-action@v1.2.4
      id: file_changes
      with:
        output: " "
    # Export changed file names for use in pre-commit action
    - name: Limit pre-commit to changed files
      if: inputs.only-changed == 'true'
      shell: bash
      run: |
        PRE_COMMIT_FILES="--files ${{ steps.file_changes.outputs.files}}"
        echo PRE_COMMIT_FILES="$PRE_COMMIT_FILES" >> $GITHUB_ENV
    # If we aren't only looking at changed files, then export the --all-files arg
    - name: Run pre-commit against all files
      if: inputs.only-changed != 'true'
      shell: bash
      run: echo PRE_COMMIT_FILES="--all-files" >> $GITHUB_ENV
    - name: Pre-commit
      # Same as above, this will install and run pre-commit for us
      if: env.PRE_COMMIT_BIN == null
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: ${{ env.PRE_COMMIT_FILES }}
    - name: Pre-commit
      # Run pre-commit directly if we found it on the PATH
      if: env.PRE_COMMIT_BIN != null
      shell: bash
      run: pre-commit run --show-diff-on-failure --color=always ${{ env.PRE_COMMIT_FILES }}
