name: Pre-commit
description: GitHub Action for running pre-commit hooks against the repository. Conditionally installs tools needed for the Action to be able to perform its duties such as `npm`, `pre-commit`, etc.
inputs:
  config-file:
    required: true
    description: The config file to present to commitlint-github-action
    default: .commitlintrc.yaml
  turo-conventional-commit:
    required: true
    description: Set this to "false" to customize conventional commit configuration
    default: "true"
  only-changed:
    required: false
    description: >-
      Set this to "true" to only run pre-commit against changed files, and not
      the entire repository
  s3-bucket-name:
    required: false
    description: S3 bucket name to cache node_modules to speed up dependency installation.
  s3-bucket-region:
    required: false
    description: S3 bucket region to cache node_modules to speed up dependency installation.
  github-token:
    required: false
    description: Sets a GitHub token that allows pre-commit to fetch private repos
outputs:
  cache-hit:
    description: Whether the cache was hit when installing dependencies
    value: ${{ steps.read_cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Setup Git Auth for Private GitHub Repos
      if: inputs.github-token != ''
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

    - name: Check for pre-commit-config.yaml
      id: pre-commit-config
      shell: bash
      run: |
        # Check for pre-commit-config.yaml
        if [[ ! -f .pre-commit-config.yaml ]]; then
          echo "::warning::No .pre-commit-config.yaml found, skipping pre-commit"
          echo "exists=false" >> $GITHUB_OUTPUT
          exit 0
        fi
    - name: Version files
      shell: bash
      run: |
        # Finding pre-commit
        # This will set an environment variable we can use to conditionally
        # install pre-commit if needed and toggle how the action runs.
        PRE_COMMIT_BIN=$(command -v pre-commit || true)
        echo "PRE_COMMIT_BIN=$PRE_COMMIT_BIN" >> $GITHUB_ENV

        # Finding python
        # This will set an environment variable we can use to conditionally
        # install python.
        PYTHON_BIN=$(command -v python || true)
        echo "PYTHON_BIN=$PYTHON_BIN" >> $GITHUB_ENV
    - name: Setup python
      # Only run this if we don't already have a pre-commit on the PATH
      if: env.PYTHON_BIN == null && env.PRE_COMMIT_BIN == null && steps.pre-commit-config.outputs.exists != 'false'
      uses: actions/setup-python@v6
    - name: Determine node version
      id: node-version
      shell: bash
      run: |
        # Read version from .node-version file if it exists, otherwise fall back to v24
        if [[ -f .node-version ]]; then
          NODE_VERSION=$(cat .node-version | tr -d '[:space:]')
          echo "version=$NODE_VERSION" >> $GITHUB_OUTPUT
        else
          # Default Node version is v24
          echo "version=24" >> $GITHUB_OUTPUT
        fi
    - name: Setup node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ steps.node-version.outputs.version }}
    - name: Commitlint
      # This version needs to be sync'd with the repo HEAD if a major version is cut
      uses: open-turo/action-pre-commit/commitlint@v3
      with:
        restore-config: "false"
        config-file: ${{ inputs.config-file }}
        turo-conventional-commit: ${{ inputs.turo-conventional-commit }}
    - name: Get changed files
      uses: dorny/paths-filter@v3
      with:
        list-files: shell
        filters: |
          changes:
            - '**'
      if: inputs.only-changed == 'true'
      id: changed-files
    - name: Select files to run pre-commit against
      shell: bash
      env:
        CHANGED_FILES: ${{ steps.changed-files.outputs.changes_files }}
        ONLY_CHANGED: ${{ inputs.only-changed }}
        CHANGED_FILES_COUNT: ${{ steps.changed-files.outputs.all_changed_files_count }}
      run: |
        echo "PRE_COMMIT_ARGS=--all-files" >> "$GITHUB_ENV"
        [[ "$CHANGED_FILES_COUNT" != "0" ]] || exit 0
        if [[ "$ONLY_CHANGED" == "true" ]]; then
          PRE_COMMIT_ARGS="--files $CHANGED_FILES"
          echo "PRE_COMMIT_ARGS=$PRE_COMMIT_ARGS" >> "$GITHUB_ENV"
        fi
    - name: Compute pre-commit cache key
      if: inputs.s3-bucket-name != ''
      id: pre_commit_cache_key
      run: |
        echo "key=${{ hashFiles('**/.pre-commit-config.yaml') }}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Load cached pre-commit hooks if available
      if: inputs.s3-bucket-name != ''
      uses: everpcpc/actions-cache@v2
      id: read_cache
      with:
        bucket: ${{ inputs.s3-bucket-name }}
        use-fallback: false
        path: ${{ runner.temp }}/${{ env.cache-name }}-${{ steps.pre_commit_cache_key.outputs.key }}
        key: ${{ env.cache-name }}-${{ steps.pre_commit_cache_key.outputs.key }}
        restore-keys: ${{ env.cache-name }}-
      env:
        AWS_REGION: ${{ inputs.s3-bucket-region }}
        cache-name: ${{ github.event.repository.name }}/cache-pre-commit
    - name: Install Pre-commit
      if: env.PRE_COMMIT_BIN == null && steps.pre-commit-config.outputs.exists != 'false'
      run: |
        pip install pre-commit
        pip freeze --local
      shell: bash
    - name: Pre-commit (from PATH)
      shell: bash
      run: pre-commit run --show-diff-on-failure --color=always ${{ env.PRE_COMMIT_ARGS }}
      env:
        PRE_COMMIT_HOME: ${{ runner.temp }}/${{ github.event.repository.name }}/cache-pre-commit-${{ steps.pre_commit_cache_key.outputs.key }}

    - name: Restore commitlint config
      if: always() && hashFiles(inputs.config-file) != '' && inputs.turo-conventional-commit == 'true'
      shell: bash
      env:
        CONFIG_FILE: ${{ inputs.config-file }}
      run: |
        # Restore the commitlint config file if we wrote it
        git checkout -- "$CONFIG_FILE" &>/dev/null || true
