name: Pre-commit
description: Run pre-commit in the current directory
inputs:
  config-file:
    required: false
    description: The config file to present to commitlint-github-action
    default: .commitlintrc.yaml
  # TODO: Determine if we want to allow an input to install dependencies,
  # such as commitlint configuration packages
runs:
  using: composite
  steps:
    # We want to just install our commitlint into the NODE_PATH below
    - name: Install dependencies
      shell: bash
      run: |
        # Install dependencies

        # This will set an environment variable we can use to conditionally
        # install pre-commit if needed and toggle how the action runs.
        echo "PRE_COMMIT_BIN=$(command -v pre-commit)" >> $GITHUB_ENV

        # Verify that the npm command exists prior to running it, and if it
        # does not exist, simply exit this step.
        command -v npm > /dev/null || { echo "Skipping npm install" && exit 0; }

        # This will install our commitlint configuration into a path we
        # can feed to the commitlint-github-action
        mkdir -p "$RUNNER_TEMP/_github_home"
        cd "$RUNNER_TEMP/_github_home" || cd "$GITHUB_WORKSPACE"
        npm install --no-save "@open-turo/commitlint-config-conventional" 2>/dev/null
        cd - &>/dev/null
    - name: Commitlint
      if: hashFiles(inputs.config-file) != '' && (github.actor!= 'dependabot[bot]') && (contains(github.head_ref, 'dependabot/github_actions/') == false)
      uses: wagoid/commitlint-github-action@v4
      with:
        configFile: ${{ inputs.config-file }}
      env:
        # This /github/home is the internal Docker mount of $RUNNER_TEMP/_github_home
        NODE_PATH: /github/home/node_modules
    - name: Setup python
      # Only run this if we don't already have a pre-commit on the PATH
      if: env.PRE_COMMIT_BIN == null
      uses: actions/setup-python@v3
    - name: Pre-commit
      # Same as above, this will install and run pre-commit for us
      if: env.PRE_COMMIT_BIN == null
      uses: pre-commit/action@v2.0.3
    - name: Pre-commit
      # Run pre-commit directly if we found it on the PATH
      if: env.PRE_COMMIT_BIN != null
      shell: bash
      run: pre-commit run --show-diff-on-failure --color=always --all-files
