name: "pre-commit"
description: "Run pre-commit in the current directory"
runs:
  using: "composite"
  steps:
    - if: hashFiles('.commitlintrc.yaml') != ''
      uses: wagoid/commitlint-github-action@v2
    - name: pre-commit
      shell: bash
      run: pre-commit run --show-diff-on-failure --color=always --all-files
