name: Pre-commit
description: Run pre-commit in the current directory
inputs:
  config-file:
    required: true
    description: The config file to present to commitlint-github-action
    default: .commitlintrc.yaml
  no-commitlint:
    required: true
    description: Set this to "true" to skip running commitlint
    default: false
  turo-conventional-commit:
    required: true
    description: Set this to "false" to customize conventional commit configuration
    default: true

runs:
  using: composite
  steps:
    - name: Find pre-commit
      shell: bash
      run: |
        # Finding pre-commit
        # This will set an environment variable we can use to conditionally
        # install pre-commit if needed and toggle how the action runs.
        echo "PRE_COMMIT_BIN=$(command -v pre-commit)" >> $GITHUB_ENV
    - name: Install Turo conventional commit configuration
      if: inputs.no-commitlint != true
      shell: bash
      run: |
        # Install Turo conventional commit configuration
        # Verify that the npm command exists prior to running it, and if it
        # does not exist, simply exit this step. This might cause later steps
        # to fail but that's their problem.
        command -v npm > /dev/null || { echo "Skipping npm install" && exit 0; }
        # This will install our commitlint configuration into a path we
        # can feed to the commitlint-github-action
        mkdir -p "$RUNNER_TEMP/_github_home"
        cd "$RUNNER_TEMP/_github_home" || cd "$GITHUB_WORKSPACE"
        npm install --no-save "@open-turo/commitlint-config-conventional" 2>/dev/null
        cd - &>/dev/null
    - name: Check commitlint config
      if: inputs.turo-conventional-commit
      shell: bash
      run: |
        # Write default commitlint config
        echo "extends: [\"@open-turo/commitlint-config-conventional\"]" > "${{ inputs.config-file }}"
    - name: Commitlint
      if: inputs.no-commitlint != true
      uses: wagoid/commitlint-github-action@v4
      with:
        configFile: ${{ inputs.config-file }}
      env:
        # This /github/home is the internal Docker mount of $RUNNER_TEMP/_github_home
        NODE_PATH: /github/home/node_modules
    - name: Setup python
      # Only run this if we don't already have a pre-commit on the PATH
      if: env.PRE_COMMIT_BIN == null
      uses: actions/setup-python@v3
    - name: Pre-commit
      # Same as above, this will install and run pre-commit for us
      if: env.PRE_COMMIT_BIN == null
      uses: pre-commit/action@v2.0.3
    - name: Pre-commit
      # Run pre-commit directly if we found it on the PATH
      if: env.PRE_COMMIT_BIN != null
      shell: bash
      run: pre-commit run --show-diff-on-failure --color=always --all-files
