name: Pre-commit
description: GitHub Action for running pre-commit hooks against the repository. Conditionally installs tools needed for the Action to be able to perform its duties such as `npm`, `pre-commit`, etc.
inputs:
  config-file:
    required: true
    description: The config file to present to commitlint-github-action
    default: .commitlintrc.yaml
  turo-conventional-commit:
    required: true
    description: Set this to "false" to customize conventional commit configuration
    default: "true"
  only-changed:
    required: false
    description: >-
      Set this to "true" to only run pre-commit against changed files, and not
      the entire repository

runs:
  using: composite
  steps:
    - name: Check for pre-commit-config.yaml
      id: pre-commit-config
      shell: bash
      run: |
        # Check for pre-commit-config.yaml
        if [[ ! -f .pre-commit-config.yaml ]]; then
          echo "::warning::No .pre-commit-config.yaml found, skipping pre-commit"
          echo "exists=false" >> $GITHUB_OUTPUT
          exit 0
        fi
    - name: Version files
      shell: bash
      run: |
        # Try to use local repo .node-version
        NODE_VERSION="${NODE_VERSION:-$(cat ".node-version" || true)}"
        # Try to use existing version
        NODE_VERSION="${NODE_VERSION:-$(node --version || true)}"
        # Try to use action default version
        NODE_VERSION="${NODE_VERSION:-$(cat "$GITHUB_ACTION_PATH/.node-version")}"
        # Write back the file if it doesn't exist
        [[ -f .node-version ]] || { echo "${NODE_VERSION#v}" > .node-version; echo "CLEAN_NODE_VERSION=true" >> "$GITHUB_ENV"; }
        echo "NODE_VERSION=${NODE_VERSION}" >> "$GITHUB_ENV"

        # Try to use local repo .python-version
        PYTHON_VERSION="${PYTHON_VERSION:-$(cat ".python-version" || true)}"
        # Try to use existing version
        PYTHON_VERSION="${PYTHON_VERSION:-$(python --version || true)}"
        # Try to use action default version
        PYTHON_VERSION="${PYTHON_VERSION:-$(cat "$GITHUB_ACTION_PATH/.python-version")}"
        # Strip leading "Python " if it exists
        PYTHON_VERSION="${PYTHON_VERSION//Python /}"
        # Write back the file if it doesn't exist
        [[ -f .python-version ]] || { echo "${PYTHON_VERSION#v}" > .python-version; echo "CLEAN_PYTHON_VERSION=true" >> "$GITHUB_ENV"; }
        echo "PYTHON_VERSION=${PYTHON_VERSION}" >> "$GITHUB_ENV"

        # Finding pre-commit
        # This will set an environment variable we can use to conditionally
        # install pre-commit if needed and toggle how the action runs.
        PRE_COMMIT_BIN=$(command -v pre-commit || true)
        echo "PRE_COMMIT_BIN=$PRE_COMMIT_BIN" >> $GITHUB_ENV

        # Finding python
        # This will set an environment variable we can use to conditionally
        # install python.
        PYTHON_BIN=$(command -v python || true)
        echo "PYTHON_BIN=$PYTHON_BIN" >> $GITHUB_ENV
    - name: Setup python
      # Only run this if we don't already have a pre-commit on the PATH
      if: env.PYTHON_BIN == null && env.PRE_COMMIT_BIN == null && steps.pre-commit-config.outputs.exists != 'false'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install tools
      # This will skip the (slow) pyenv install if we triggered the above
      uses: open-turo/action-setup-tools@v1
    - name: Install @commitlint/cli
      shell: bash
      run: |
        npm install --no-save --no-package-lock --no-audit --no-fund \
          --prefix "$RUNNER_TEMP" "@commitlint/cli"
        echo "$RUNNER_TEMP/node_modules/.bin" >> $GITHUB_PATH
        echo "NODE_PATH=$RUNNER_TEMP/node_modules" >> $GITHUB_ENV
    - name: Use default conventional commit config
      if: inputs.turo-conventional-commit == 'true'
      shell: bash
      run: |
        # Write default commitlint config in the workspace.
        echo "extends: [\"@open-turo/commitlint-config-conventional\"]" \
          > "${{ inputs.config-file }}"
        # XXX(shakefu): We have to list @commitlint/cli here otherwise `npm
        # install` will try to remove it from the above step. There is no way to
        # prevent this behavior that I'm aware of.
        npm install --no-save --no-package-lock --no-audit --no-fund \
          --prefix "$RUNNER_TEMP" \
          "@open-turo/commitlint-config-conventional" \
          "@commitlint/cli"
    - name: Commitlint
      if: hashFiles(inputs.config-file) != ''
      shell: bash
      run: |
        # Commitlint
        # Look for the base ref to compare against the current head in the
        # pull_request event metadata.
        if [[ -z "$FROM" ]]; then
          FROM="${{ github.event.pull_request.base.ref }}"
          if [[ -n "$FROM" ]]; then
            echo "::notice::Parsing base ref '$FROM'"
            # If we do have the base ref, it can be a branch name, so we want to
            # parse it. This will be a pass through for a SHA
            # via the event context, and we should try to find the default
            # branch instead (see below)
            if ! git show-ref --hash "$FROM" &>/dev/null; then
              # No such ref, so we try the next step
              FROM=""
            else
              FROM="$(git show-ref --hash "$FROM" | tail -n1)"
            fi
          fi
        fi
        # If we don't have a base ref, we try to find the history to the default
        # branch, e.g. main, which should be a sane check.
        if [[ -z "$FROM" ]]; then
          # This finds the default branch name from the remote information, e.g. "main", and then parses it to a SHA
          FROM="$(git show-ref --hash "$(git remote show $(git remote -v | grep push | awk '{print $2}') | grep 'HEAD branch' | awk '{print $3}')" | tail -n1)"
          echo "::notice::Could not find base ref, trying to use default branch"
          if ! git merge-base --is-ancestor "$FROM" HEAD; then
            echo "::warning::Default branch is not an ancestor of HEAD"
            FROM=""
          fi
        fi
        # If the pull_request event metadata doesn't exist, try to grab the
        # "before" commit from the push event metadata. This will usually only
        # give us a single commit to check, but it'll be the latest one.
        if [[ -z "$FROM" ]]; then
          # This is a SHA so no parsing needed
          FROM="${{ github.event.before }}"
          echo "::warning::Could not find ancestor ref, falling back"
          if ! git merge-base --is-ancestor "$FROM" HEAD; then
            echo "::warning::Before commit $FROM is not an ancestor of HEAD"
          else
            echo "::notice::Checking commits since $FROM (usually the latest commit)."
          fi
        fi
        # Default to looking at the last 20 commits otherwise.
        if [[ -z "$FROM" ]]; then
          FROM="HEAD~20"
          echo "::warning::Could not find commit range for commitlint"
          echo "::notice::Checking 20 most recent commit messages."
        fi
        CONFIG_FILE="${{ inputs.config-file }}"
        if [[ -n "$CONFIG_FILE" ]]; then
          CONFIG_FILE="--config $CONFIG_FILE"
        fi
        echo "::notice::Running commitlint"
        commitlint \
          $CONFIG_FILE \
          --verbose \
          --color \
          --from "$FROM" \
          --to HEAD
    - name: Get changed files
      uses: tj-actions/changed-files@v40
      if: inputs.only-changed == 'true'
      id: changed-files
    - name: Select files to run pre-commit against
      shell: bash
      run: |
        echo "PRE_COMMIT_ARGS=--all-files" >> "$GITHUB_ENV"
        [[ "${{ steps.changed-files.outputs.any_changed }}" == "true" ]] || exit 0
        if [[ "${{ inputs.only-changed }}" == "true" ]]; then
          PRE_COMMIT_ARGS="--files ${{ steps.changed-files.outputs.files}}"
          echo "PRE_COMMIT_ARGS=$PRE_COMMIT_ARGS" >> "$GITHUB_ENV"
        fi
    - name: Pre-commit (action)
      # Same as above, this will install and run pre-commit for us
      if: env.PRE_COMMIT_BIN == null && steps.pre-commit-config.outputs.exists != 'false'
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: ${{ env.PRE_COMMIT_ARGS }}
    - name: Pre-commit (from PATH)
      # Run pre-commit directly if we found it on the PATH
      if: env.PRE_COMMIT_BIN != null && steps.pre-commit-config.outputs.exists != 'false'
      shell: bash
      run: pre-commit run --show-diff-on-failure --color=always ${{ env.PRE_COMMIT_ARGS }}
    - name: Clean up version files
      if: always()
      shell: bash
      run: |
        # Clean up version files if we wrote them
        [[ "${{ env.CLEAN_PYTHON_VERSION }}" == "" ]] || rm .python-version
        [[ "${{ env.CLEAN_NODE_VERSION }}" == "" ]] || rm .node-version
    - name: Restore commitlint config
      if: always() && hashFiles(inputs.config-file) != '' && inputs.turo-conventional-commit == 'true'
      shell: bash
      run: |
        # Restore the commitlint config file if we wrote it
        git checkout -- "${{ inputs.config-file }}" &>/dev/null || true
