#!/usr/bin/env bash

set -e

for i in "$@"; do
  # ignore if the file does not end with /action.yaml
  if [[ "$i" != *"action.yaml" ]]; then
    echo "skipping: ${i}"
    continue
  fi
  readme_file=$(dirname "$i")/README.md
  echo npx action-docs@^1 --no-banner -a "${i}" --update-readme "${readme_file}"
  npx action-docs@^1 --no-banner -a "${i}" --update-readme "${readme_file}"
done
