name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - if: (github.actor!= 'dependabot[bot]') && (contains(github.head_ref, 'dependabot/github_actions/') == false)
        uses: wagoid/commitlint-github-action@v4
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3

  # test action works running from the graph
  action:
    name: Action test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
      - uses: ./
